spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:h2:mem:orders
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
server:
  port: 8200
springdoc:
  swagger-ui:
    path: /sw